### ISSUE TITLE
The cpu memory keeps increasing, and when it is full, an error got!

### ISSUE THREAD

**Issue by nizhihao** [DeNA/HandyRL#189]
Hi, When I try to train this code with python main.py --train  in my local computer. It's always happen that the cpu memory keeps increasing and when it is full, an error is reported.  I think this problem cause by the memory out.

Traceback (most recent call last):
  File "/home/user/.conda/envs/spinningup_nzh/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/user/.conda/envs/spinningup_nzh/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/nzh_projects/kaggle-environments-master/kaggle_agent/HandyRL/handyrl/connection.py", line 190, in _receiver
    data, cnt = conn.recv()
  File "/home/user/.conda/envs/spinningup_nzh/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/user/.conda/envs/spinningup_nzh/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/user/.conda/envs/spinningup_nzh/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/user/.conda/envs/spinningup_nzh/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/user/.conda/envs/spinningup_nzh/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/nzh_projects/kaggle-environments-master/kaggle_agent/HandyRL/handyrl/connection.py", line 175, in _sender
    conn.send(next(self.send_generator))
  File "/home/user/.conda/envs/spinningup_nzh/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/user/.conda/envs/spinningup_nzh/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/home/user/.conda/envs/spinningup_nzh/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

Because my Memory only have 32G, so i have try to turn the max_episodes to the 200000. when the number of the sample at 20w, the memoey use_rate about 95%, but this code still  occupy the more cpu memory with continuous sampling. In my Option, I think when the sample number more than max_episodes, the replay buffer will delete the old sample. but i dont know why the memory still increase.

could you give me some ideas. and how can i solve this problem(not restart). Thanks very much!

**Comment by ikki407** [comment]
Thank you for your report!
I think your error is perhaps the same thing as commented in https://github.com/DeNA/HandyRL/issues/184#issuecomment-824205912

Could you check it out? Thanks.

**Comment by digitalspecialists** [comment]
Similar issue here. 

Working setup in March: Cloud GPU server, 4x16 CPU workers. Could run 500,000 buffer and memory plateaued at 48G. 

Setup now with current codebase: Local GPU, local 64-thread CPU. 60G used in 100,000 matches. Set buffer to 40,000 and memory continues to be consumed past 40k and right to exhaustion of 120G.

**Comment by YuriCat** [comment]
Thank you for your detailed report!
Since episodes among agents at the beginning are very short in Hungry Geese, it's not strange that used memory increases after the replay buffer is filled with episodes.

If you increase `compress_steps` you can save memory, while the speed of making batches will slow down.

**Comment by nizhihao** [comment]
Ok! thanks your reply!
First, Let me try to restart epoch when memory is full. because the pre-trained model have get some skills, so every episode will hold  the same length I think.
second, I try to decrease max_episode and train it again.

and if I increase compress_steps, I will lose the trajectory's precision  or only slow down the train?

**Comment by digitalspecialists** [comment]
> Thank you for your detailed report!
> Since episodes among agents at the beginning are very short in some environments, it's not strange that used memory increases after the replay buffer is filled with episodes.
> 
> If you increase `compress_steps` you can save memory, while the speed of making batches will slow down.

If I set initial/maximum_episodes to 10k/14k and even mem_used_ratio to 0.04 (6GB) as a safeguard it continues to blow 128GB with the 14k buffer. Various python memory profiling tools show the deque isn't leaking but no other candidate. It could be something other than the replay buffer - model deepcopy's? I've also tried running server/client separately on the same machine.

It could be my rig (hence deleting issue earlier). I intend to try on a cloud compute to exclude/identify my rig as the issue. My rig shows no errors with memory check tools. Then an earlier commit.

**Comment by YuriCat** [comment]
@nizhihao 
There is no precision problem with `compress_steps`.
It only slows down the speed of making batches. If this speed is not enough to use GPUs without a break, training will slow down. So if you prepared batchers enough to use GPUs continuously, there is no problem, while batchers also spend CPU time.

**Comment by YuriCat** [comment]
@digitalspecialists 
Thank you for your helpful report!
So, is there a problem around CUDA 11.2? We'll look into it when we get a chance.

**Comment by nizhihao** [comment]
@YuriCat Hello, I read your code! It's very beautiful!
And maybe I find the reason why  the memory is always up. 
In train.py
`        while len(self.trainer.episodes) > self.args['maximum_episodes']:
            self.trainer.episodes.popleft()
`
Although pop the episode that over the maximum_episodes,  the duque's sizeof don't take away and the remove one still occupy the memory! 

Looking forward to your reply！Thanks！

**Comment by digitalspecialists** [comment]
@YuriCat This issue seems to persist for me. 

Clearly later episodes take more space than earlier episodes due to more successful agents. 

And that self.args['maximum_episodes'] is capped when we first hit 95% of mem. 

But self.args['maximum_episodes'] is never further reduced as the sizeof the deque continues to grow.

The replay buffer mem usage continues to grow inside the capped self.args['maximum_episodes']

I think what is needed is to self.trainer.episodes.popleft() while mem_used_ratio >= 0.95

**Comment by YuriCat** [comment]
@digitalspecialists 
I understand what you pointed out. Yes, that's necessary.

**Comment by digitalspecialists** [comment]
@ikki407 thanks for your change but it fails. For me training collapses catastrophically at 95%. Falls off a cliff to random/0.

I think it may be because psutil.virtual_memory() doesn't report memory release fast enough. Though even then ...

This will reproduce

```
from collections import deque
import psutil
import numpy as np

config_maximum_episodes = 1e15
self_trainer_episodes = deque()

mem_thresh = 85

episodes = np.random.rand(10000,10000)

c=0
while True:
    
    self_trainer_episodes.extend([e for e in episodes if e is not None])

    mem_percent = psutil.virtual_memory().percent
    mem_ok = mem_percent <= mem_thresh
    maximum_episodes = config_maximum_episodes if mem_ok else int(len(self_trainer_episodes) * mem_thresh / mem_percent)
    if c%10000==0 or (c%1000==0 and maximum_episodes != config_maximum_episodes): 
        print('mem_percent:', mem_percent, 
              'maximum_episodes:', maximum_episodes)

    while len(self_trainer_episodes) > config_maximum_episodes:
        self_trainer_episodes.popleft()
    
    c+=1

```
On a 32GB machine, output

```
mem_percent: 32.3 maximum_episodes: 1000000000000000.0
mem_percent: 61.4 maximum_episodes: 1000000000000000.0
mem_percent: 87.5 maximum_episodes: 184581142
mem_percent: 90.7 maximum_episodes: 187440463
mem_percent: 94.8 maximum_episodes: 188300105
mem_percent: 98.9 maximum_episodes: 189088473
mem_percent: 99.4 maximum_episodes: 196688631

```

... and dies
